// ============================================
// LUXE STORE — DATA STORE
// ============================================

export const PRODUCTS = [
  {
    id: 1,
    name: "Pro Wireless Headphones",
    category: "Electronics",
    price: 299,
    originalPrice: 399,
    emoji: "🎧",
    rating: 4.8,
    reviews: 2847,
    badge: "Best Seller",
    badgeType: "hot",
    description: "Experience studio-quality sound with 40-hour battery life and active noise cancellation. Premium comfort with memory foam ear cushions.",
    colors: ["#0F172A", "#2563EB", "#EF4444", "#FFFFFF"],
    sizes: null,
    inStock: true,
  },
  {
    id: 2,
    name: "Minimal Smart Watch",
    category: "Electronics",
    price: 449,
    originalPrice: 549,
    emoji: "⌚",
    rating: 4.9,
    reviews: 1923,
    badge: "New",
    badgeType: "new",
    description: "Next-generation smartwatch with health tracking, GPS, and a stunning AMOLED display. 7-day battery with always-on mode.",
    colors: ["#0F172A", "#D4AF37", "#C0C0C0"],
    sizes: null,
    inStock: true,
  },
  {
    id: 3,
    name: "Designer Leather Jacket",
    category: "Fashion",
    price: 189,
    originalPrice: 289,
    emoji: "🧥",
    rating: 4.7,
    reviews: 643,
    badge: "35% OFF",
    badgeType: "sale",
    description: "Premium genuine leather jacket with tailored fit. Timeless design that transitions seamlessly from casual to formal.",
    colors: ["#0F172A", "#5C4033", "#D2691E"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: 4,
    name: "Luxury Coffee Maker",
    category: "Home",
    price: 249,
    originalPrice: null,
    emoji: "☕",
    rating: 4.6,
    reviews: 1204,
    badge: null,
    badgeType: null,
    description: "Barista-quality coffee at home. 15-bar pressure, built-in grinder, and smart brewing profiles for the perfect cup every time.",
    colors: ["#C0C0C0", "#0F172A", "#D4AF37"],
    sizes: null,
    inStock: true,
  },
  {
    id: 5,
    name: "Sunglasses Premium",
    category: "Accessories",
    price: 159,
    originalPrice: 199,
    emoji: "🕶️",
    rating: 4.5,
    reviews: 892,
    badge: "Trending",
    badgeType: "hot",
    description: "Polarized UV400 lenses with titanium frames. Handcrafted in Italy with a case and cleaning kit included.",
    colors: ["#0F172A", "#D4AF37", "#C0C0C0", "#8B4513"],
    sizes: null,
    inStock: true,
  },
  {
    id: 6,
    name: "Yoga Mat Premium",
    category: "Lifestyle",
    price: 89,
    originalPrice: 129,
    emoji: "🧘",
    rating: 4.8,
    reviews: 3210,
    badge: "Sale",
    badgeType: "sale",
    description: "Eco-friendly TPE mat with alignment lines, non-slip surface, and carrying strap. Ideal for yoga, pilates, and meditation.",
    colors: ["#7C3AED", "#059669", "#0F172A", "#DC2626"],
    sizes: null,
    inStock: true,
  },
  {
    id: 7,
    name: "Sneakers Urban Pro",
    category: "Fashion",
    price: 219,
    originalPrice: null,
    emoji: "👟",
    rating: 4.9,
    reviews: 5102,
    badge: "New",
    badgeType: "new",
    description: "Premium comfort sneakers with responsive foam sole, breathable mesh upper, and sustainable materials.",
    colors: ["#FFFFFF", "#0F172A", "#2563EB", "#EF4444"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    inStock: true,
  },
  {
    id: 8,
    name: "Minimalist Backpack",
    category: "Accessories",
    price: 149,
    originalPrice: 189,
    emoji: "🎒",
    rating: 4.7,
    reviews: 1567,
    badge: "Popular",
    badgeType: "hot",
    description: "Water-resistant 25L backpack with laptop sleeve, USB charging port, and ergonomic shoulder straps. Business meets adventure.",
    colors: ["#0F172A", "#64748B", "#D4AF37"],
    sizes: null,
    inStock: true,
  },
];

export const CATEGORIES = [
  {
    id: 1,
    name: "Electronics",
    emoji: "📱",
    gradient: "linear-gradient(135deg, #1E3A5F, #0F172A)",
    count: 124,
    label: "Tech & Gadgets",
  },
  {
    id: 2,
    name: "Fashion",
    emoji: "👗",
    gradient: "linear-gradient(135deg, #4C1D95, #1E1B4B)",
    count: 287,
    label: "Style & Apparel",
  },
  {
    id: 3,
    name: "Home",
    emoji: "🏡",
    gradient: "linear-gradient(135deg, #14532D, #052e16)",
    count: 193,
    label: "Living & Decor",
  },
  {
    id: 4,
    name: "Accessories",
    emoji: "💎",
    gradient: "linear-gradient(135deg, #7C2D12, #431407)",
    count: 156,
    label: "Finish Your Look",
  },
  {
    id: 5,
    name: "Lifestyle",
    emoji: "✨",
    gradient: "linear-gradient(135deg, #0C4A6E, #082F49)",
    count: 98,
    label: "Wellness & More",
  },
];

export const TRUST_ITEMS = [
  {
    id: 1,
    icon: "🚚",
    title: "Free Shipping",
    description: "On all orders over $50",
  },
  {
    id: 2,
    icon: "🔒",
    title: "Secure Payments",
    description: "256-bit SSL encryption",
  },
  {
    id: 3,
    icon: "🎧",
    title: "24/7 Support",
    description: "Expert help anytime",
  },
  {
    id: 4,
    icon: "↩️",
    title: "Easy Returns",
    description: "30-day return policy",
  },
];
